# Generated by Django 5.1.4 on 2025-01-04 19:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_banner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "verbose_name": "Hình ảnh quảng cáo",
                "verbose_name_plural": "Hình ảnh quảng cáo",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Danh mục sản phẩm",
                "verbose_name_plural": "Danh mục sản phẩm",
            },
        ),
        migrations.AlterModelOptions(
            name="color",
            options={
                "verbose_name": "Màu sắc sản phẩm",
                "verbose_name_plural": "Màu sắc sản phẩm",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={
                "verbose_name": "Hình ảnh",
                "verbose_name_plural": "Hình ảnh sản phẩm",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Quản lý sản phẩm",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseinvoice",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Hóa đơn nhập hàng",
                "verbose_name_plural": "Hóa đơn nhập hàng",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseinvoiceline",
            options={
                "ordering": ["invoice"],
                "verbose_name": "Chi tiết nhập hàng",
                "verbose_name_plural": "Chi tiết nhập hàng",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Quản lý đánh giá",
            },
        ),
        migrations.AlterModelOptions(
            name="size",
            options={
                "verbose_name": "Kích thước sản phẩm",
                "verbose_name_plural": "Kích thước sản phẩm",
            },
        ),
        migrations.AlterModelOptions(
            name="stockquantity",
            options={
                "verbose_name": "Số lượng tồn kho",
                "verbose_name_plural": "Số lượng tồn kho",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="category_id",
            field=models.CharField(
                max_length=10,
                primary_key=True,
                serialize=False,
                verbose_name="Mã danh mục",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Tên danh mục"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products.category",
                verbose_name="Danh mục cha",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="color_id",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, verbose_name="Mã màu"
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên"),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Mã hình ảnh"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.ImageField(upload_to="products/", verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products", to="products.category", verbose_name="Danh mục"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(
                related_name="products", to="products.color", verbose_name="Màu sắc"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="product",
            name="import_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Giá nhập",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên sản phẩm"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(
                max_length=10,
                primary_key=True,
                serialize=False,
                verbose_name="Mã sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sell_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Giá bán",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(
                related_name="products", to="products.size", verbose_name="Kích cỡ"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Nhập bởi",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="invoice_id",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="Mã hóa đơn",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="supplier",
            field=models.CharField(max_length=255, verbose_name="Nhà cung cấp"),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Tổng tiền"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoiceline",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.purchaseinvoice",
                verbose_name="Mã hóa đơn",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoiceline",
            name="invoiceLine_id",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="Mã chi tiết hóa đơn",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoiceline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Giá"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoiceline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoiceline",
            name="quantity",
            field=models.IntegerField(verbose_name="Số lượng"),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Bình luận"),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(verbose_name="Số sao"),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Mã đánh giá"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên"),
        ),
        migrations.AlterField(
            model_name="size",
            name="size_id",
            field=models.CharField(
                max_length=10,
                primary_key=True,
                serialize=False,
                verbose_name="Mã kích thước",
            ),
        ),
        migrations.AlterField(
            model_name="stockquantity",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_quantities",
                to="products.color",
                verbose_name="Màu sắc",
            ),
        ),
        migrations.AlterField(
            model_name="stockquantity",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Mã"
            ),
        ),
        migrations.AlterField(
            model_name="stockquantity",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_quantities",
                to="products.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="stockquantity",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_quantities",
                to="products.size",
                verbose_name="Kích cỡ",
            ),
        ),
        migrations.AlterField(
            model_name="stockquantity",
            name="stock",
            field=models.IntegerField(verbose_name="Số lượng tồn kho"),
        ),
    ]
