# Generated by Django 5.1.4 on 2025-01-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Quản lý người dùng",
                "verbose_name_plural": "Quản lý người dùng",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(null=True, verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Họ và tên"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Nam"), ("Female", "Nữ"), ("Other", "Khác")],
                default="Other",
                max_length=10,
                null=True,
                verbose_name="Giới tính",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Còn hoạt động"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Là nhân viên"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="Mật khẩu"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=15, null=True, unique=True, verbose_name="Số điện thoại"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Customer", "Khách hàng"),
                    ("Admin", "Quản lý"),
                    ("Staff", "Nhân viên"),
                ],
                default="Customer",
                max_length=10,
                verbose_name="Vai trò",
            ),
        ),
    ]
